= MicroProfile Training

This repository holds the training for the microprofile specifications.
After working through the training one should be able to understand the most common microprofile specifications, their impacts, their interoperability and how to use them properly in real time applications.

This training is based on the link:https://jakarta.ee/release/8/[Jakarta-EE 8.0] link:https://projects.eclipse.org/projects/technology.microprofile/releases/microprofile-4.1[(Eclipse MicroProfile 4.1)] specification and the link:https://www.wildfly.org/[Wildfly 26.1.3.Final] application server.

== Used Tools

To get the application running you need the following software installed:

. link:https://jdk.java.net/java-se-ri/17[OpenJDK 17]
. link:https://www.wildfly.org/downloads/#26.1.3.Final[Wildfly 26.1.3.FINAL (Jakarta EE 8 Full & Web Distribution)]
. link:https://maven.apache.org/download.cgi?Preferred=ftp://ftp.osuosl.org/pub/apache/[Maven 3.x.x]
. link:https://docs.docker.com/engine/[Docker]
. link:https://docs.docker.com/compose/[Docker Compose]

== Accessing the application

The application can be accessed via `http://localhost:8080/mptraining/api/welcome`.

Follow the instructions to work through the exercises.

IMPORTANT: When running in an IDE the actual port will depend on your configuration.

== Setup

=== Building the application

Before you progress further into the setup of the training run `mvn clean install` in the projects root directory.
This will build the project and also gather some dependencies needed further in the setup.

=== Running in an IDE

Refer to the documentation of the IDE of your choice, which must provide integration for Wildfly/JBoss servers, for how to set up the project.

Configure you wildfly to use microprofile configuration by adding `-c standalone-microprofile.xml` to your startup script in your run configuration.

IMPORTANT: When running in an IDE you may have to add this to both the run and debug configurations if you use both of them.

After the first startup you need to run the `scripts.cli` on your wildfly with `jboss-cli` for further configuration.
The scripts.cli references some files (e.g. postgres driver) in the projects build folder (target).

Therefore you have to run the cli script from the projects root directory:
`<your-JBOSS_HOME-directory>/bin/jboss-cli.sh --file=infrastructure/wildfly/scripts.cli --connect`

Restart your server after the script finished.

IMPORTANT: You need to run the server with the `standalone-microprofile.xml` otherwise microprofile extensions are not available.

=== Starting up the infrastructure

Change to the `infrastructure` directory and run `docker-compose up -d`.

To access the infrastructure tools use one of the following links:

* link:http://localhost:19090[Prometheus]
* link:http://localhost:13000[Grafana]
* link:http://localhost:18080[Keycloak]
* link:http://localhost:16686[Jaeger-UI]

The credentials for all applications can be found in our link:https://gepardec.github.io/microprofile-training/#infrastructure-guide[infrastructure guide].

== Further documentation

See our link:https://gepardec.github.io/microprofile-training/[WIKI] for contribution guidelines and deeper documentation about this project.
