= MicroProfile Training

This repository provides training on the most common MicroProfile specifications. Upon completion, you'll understand their impact, interoperability, and how to apply them in real-world applications.

This training is based on the following specifications:

- link:https://jakarta.ee/specifications/coreprofile/10/[Jakarta EE Core Profile 10]
- link:https://projects.eclipse.org/projects/technology.microprofile/releases/microprofile-7.0[MicroProfile 7.0]

The implementation is provided by:

- link:https://www.wildfly.org[Wildfly 36.0.1.Final]

== Used Tools

To get the application running you need the following software installed:

. link:https://openjdk.org/projects/jdk/21/[OpenJDK 21]
. link:https://maven.apache.org/download.cgi[Maven 3.9.x]
. link:https://docs.docker.com/engine/[Docker]

== Setup

=== Starting up the infrastructure

Change to the `infrastructure` directory and run `docker compose up -d`.

To access the infrastructure tools use one of the following links:

* link:http://localhost:3000[Grafana]
* link:http://localhost:8080[Keycloak]

The credentials for all applications can be found in `docker-compose.yml` located in the infrastructure folder.

If you want to tear down the infrastructure change to the `infrastructure` directory and run `docker compose down -v`.

=== Starting up Wildfly

Change to the root directory of the project and run `mvn clean install wildfly:dev`.
By starting Wildfly in development mode, the server is watching for changes and will automatically redeploy your application.

If necessary, you can attach a debugger in your IDE for stepping in your code. Append `-Dwildfly.debug=true -Dwildfly.debug.port=5005` to your mvn command to do so.

== Accessing the application

The application can be accessed via `http://localhost:8180/mptraining/api/welcome`.

Follow the instructions to work through the exercises.
