= Microprofile Training

This repository holds the training for the microprofile specifications.
After working through the training one should be able to understand the most common microprofile specifications, their impacts, their interoperability and how to use them properly in real time applications.

This training is based on the link:https://jakarta.ee/release/8/[Jakarta-EE 8.0] link:https://projects.eclipse.org/projects/technology.microprofile/releases/microprofile-3.3[(Eclipse MicroProfile 3.3)] specification and the link:https://www.wildfly.org/[Wildfly 22.0.0.Final] application server.

IMPORTANT: This repository is in working progress, and as long as you see this message you cannot rely on consistency between the doc and the current implementation state.

== Used Tools

To get the application running you need the following software installed:

. link:https://jdk.java.net/java-se-ri/11[OpenJDK 11]
. link:https://www.wildfly.org/downloads/[Wildfly 22.0.0.FINAL (Jakarta EE 8 Full & Web Distribution)]
. link:https://maven.apache.org/download.cgi?Preferred=ftp://ftp.osuosl.org/pub/apache/[Maven 3.6.x]

== Accessing the application

The application can be accessed via `http://localhost:8080/mptraining/welcome`. +

Follow the instructions to work through the exercises.

IMPORTANT: When running in an IDE the actual port will depend on your configuration.

== Running in standalone

Run the application with `./mvnw wildfly:run`.

IMPORTANT: In this mode you won't be able to hot-code deploy.

== Running in an IDE

Refer to the documentation of the IDE of your choice, which must provide integration for Wildfly/JBoss servers, for how to set up the project.

IMPORTANT: You need to run the server with the `standalone-microprofile.xml` configuration.