---
openapi: 3.1.0
paths:
  /cheetahs:
    post:
      description: A new cheetah is born
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Cheetah"
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Cheetah"
    get:
      summary: List full with cheetahs.
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Cheetah"
        "404":
          description: No Cheetah found
    delete:
      description: Removes a cheetah from the coalition
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Cheetah"
        required: true
      responses:
        "202":
          description: Operation executed successfully
        "204":
          description: No Cheetah found
  /basic/openapi:
    get:
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: string
  /basic/openapi/annotations:
    get:
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: string
  /basic/openapi/document:
    get:
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: string
  /basic/openapi/filter:
    get:
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: string
  /basic/openapi/index:
    get:
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: string
  /basic/openapi/staticDocument:
    get:
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: string
components:
  schemas:
    Cheetah:
      description: POJO that represents a cheetah
      type: object
      properties:
        age:
          type: integer
          format: int32
        name:
          type: string
        weight:
          type: number
          format: double
      required:
      - name
info:
  title: microprofile-training-1.0.0-SNAPSHOT.war
  version: "1.0"
servers:
- url: /mptraining
