version: '3.8'

volumes:
  prometheus_data:
  grafana_data:
  postgres_data:

services:
  prometheus:
    image: prom/prometheus:v2.30.0
    ports:
      - "19090:9090"
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    extra_hosts:
      - "host.docker.internal:host-gateway"

  grafana:
    image: grafana/grafana:8.1.5
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: 'admin@123'
    ports:
      - "13000:3000"
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - grafana_data:/var/lib/grafana
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - prometheus

  postgres:
    image: postgres:13.4
    ports:
      - "15432:5432"
    volumes:
      - ./postgres/01_init-user-db.sh:/docker-entrypoint-initdb.d/01_init-user-db.sh
      - ./postgres/02_init-mptraining.sh:/docker-entrypoint-initdb.d/02_init-mptraining.sh
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 'admin@123'

  keycloak:
    image: quay.io/keycloak/keycloak:15.0.2
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_SCHEMA: public
      DB_DATABASE: keycloak
      DB_USER: admin
      DB_PASSWORD: 'admin@123'
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: 'admin@123'
    command:
      - "-b 0.0.0.0"
      - "-Dkeycloak.import=/opt/jboss/keycloak/microprofile-realm.json"
    ports:
      - "18080:8080"
    volumes:
      - ./keycloak/v3_realm-export.json:/opt/jboss/keycloak/microprofile-realm.json:ro
    depends_on:
      - postgres

  jaeger:
      image: jaegertracing/all-in-one:1.27
      ports:
        - "16831:6831/udp"
        - "16686:16686"
      depends_on:
        - prometheus