version: '3.8'

volumes:
  postgres_data:

services:
  otel-lgtm:
    image: grafana/otel-lgtm
    ports:
      - "3000:3000"
      - "4317:4317"
      - "4318:4318"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: 'admin@123'

  postgres:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    image: custom-postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 'admin@123'

  keycloak:
    build:
      context: ./keycloak
      dockerfile: Dockerfile
    image: custom-keycloak
    environment:
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8080
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: 'admin@123'
    command: "start-dev --import-realm"
    ports:
      - "8080:8080"
