title: MicroProfile done right
email: thomas.herzog@gepardec.com
description: > # this means to ignore newlines until "baseurl:"
  This is WIKI page for the microprofile-training project

timezone: Europe/Vienna
encoding: UTF-8
lsi: false
markdown: kramdown
highlighter: rouge
theme: jekyll-theme-cayman
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
kramdown:
  auto_ids: true
  entity_output: as_char
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  input: GFM
  hard_wrap: false
  footnote_nr: 1
  show_warnings: false