---
openapi: 3.0.3
info:
  title: microprofile-training-1.0.0-SNAPSHOT.war
  version: "1.0"
servers:
  - url: /mptraining
paths:
  /cheetahs:
    get:
      summary: List full with cheetahs.
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Cheetah'
        "404":
          description: No Cheetah found
    post:
      description: A new cheetah is born
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Cheetah'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                uniqueItems: true
                type: array
                items:
                  $ref: '#/components/schemas/Cheetah'
    delete:
      description: Removes a cheetah from the coalition
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Cheetah'
      responses:
        "202":
          description: Operation executed successfully
        "204":
          description: No Cheetah found
components:
  schemas:
    Cheetah:
      description: POJO that represents a cheetah
      required:
        - name
      type: object
      properties:
        age:
          format: int32
          type: integer
        name:
          type: string
        weight:
          format: double
          type: number